"""alter_historico_compras_table

Revision ID: 681ea89ff843
Revises: 76ad00ae4d16
Create Date: 2026-05-07 10:31:22.709758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681ea89ff843'
down_revision: Union[str, Sequence[str], None] = '76ad00ae4d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_compras', sa.Column('supermercado', sa.String(length=100), nullable=True))
    op.add_column('historico_compras', sa.Column('lista_itens_comprados', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_historico_compras_supermercado'), 'historico_compras', ['supermercado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_compras_supermercado'), table_name='historico_compras')
    op.drop_column('historico_compras', 'lista_itens_comprados')
    op.drop_column('historico_compras', 'supermercado')
    # ### end Alembic commands ###
