"""create_tables

Revision ID: 76ad00ae4d16
Revises: 
Create Date: 2026-04-28 21:31:22.222515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ad00ae4d16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('pergunta', sa.String(length=500), nullable=True),
    sa.Column('resposta', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_log_id'), 'chat_log', ['id'], unique=False)
    op.create_table('historico_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.Column('gasto_valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_compras_data_compra'), 'historico_compras', ['data_compra'], unique=False)
    op.create_index(op.f('ix_historico_compras_id'), 'historico_compras', ['id'], unique=False)
    op.create_table('lista_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('nome_item', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_compras_data_criacao'), 'lista_compras', ['data_criacao'], unique=False)
    op.create_index(op.f('ix_lista_compras_id'), 'lista_compras', ['id'], unique=False)
    op.create_index(op.f('ix_lista_compras_nome_item'), 'lista_compras', ['nome_item'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lista_compras_nome_item'), table_name='lista_compras')
    op.drop_index(op.f('ix_lista_compras_id'), table_name='lista_compras')
    op.drop_index(op.f('ix_lista_compras_data_criacao'), table_name='lista_compras')
    op.drop_table('lista_compras')
    op.drop_index(op.f('ix_historico_compras_id'), table_name='historico_compras')
    op.drop_index(op.f('ix_historico_compras_data_compra'), table_name='historico_compras')
    op.drop_table('historico_compras')
    op.drop_index(op.f('ix_chat_log_id'), table_name='chat_log')
    op.drop_table('chat_log')
    # ### end Alembic commands ###
