"""create_users_table_and_relationships

Revision ID: eeb5c4b9a840
Revises: 681ea89ff843
Create Date: 2026-05-21 15:38:12.390885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eeb5c4b9a840'
down_revision: Union[str, Sequence[str], None] = '681ea89ff843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phonenumber', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('chat_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('chat_log', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.alter_column('chat_log', 'resposta',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.create_foreign_key(None, 'chat_log', 'users', ['user_id'], ['id'])
    op.drop_column('chat_log', 'user')
    op.add_column('historico_compras', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('historico_compras', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'historico_compras', 'users', ['user_id'], ['id'])
    op.drop_column('historico_compras', 'user')
    op.add_column('lista_compras', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('lista_compras', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'lista_compras', 'users', ['user_id'], ['id'])
    op.drop_column('lista_compras', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_compras', sa.Column('user', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'lista_compras', type_='foreignkey')
    op.drop_column('lista_compras', 'user_name')
    op.drop_column('lista_compras', 'user_id')
    op.add_column('historico_compras', sa.Column('user', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'historico_compras', type_='foreignkey')
    op.drop_column('historico_compras', 'user_name')
    op.drop_column('historico_compras', 'user_id')
    op.add_column('chat_log', sa.Column('user', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'chat_log', type_='foreignkey')
    op.alter_column('chat_log', 'resposta',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('chat_log', 'user_name')
    op.drop_column('chat_log', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
